/**
 * Common base class for all structured generated by Kaitai Struct.
 * Stores stream object that this object was parsed from in {@link #_io}.
 */
public class KaitaiStruct {
    /**
     * Stream object that this KaitaiStruct-based structure was parsed from.
     */
    protected KaitaiStream _io;

    public KaitaiStruct(KaitaiStream _io) {
        this._io = _io;
    }

    public KaitaiStream _io() { return _io; }
}